### ISSUE TITLE
Incorrect key length of 32bit key

### ISSUE THREAD

**Issue by naushrambo** [ilnicki/laravel-encryption#4]
Error: The only supported ciphers are [AES-128-CBC, AES-256-CBC] with the correct key lengths.
    at new Encrypter (/home/runner/CreepyEvenEllipse/node_modules/laravel-encryption/src/Illuminate/Encryption/Encrypter.js:28:19)
    at /home/runner/CreepyEvenEllipse/index.js:3:17
    at Script.runInContext (vm.js:130:18)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

**Comment by humurabbi** [comment]
Just change the algorithm for AES-128-CBC to AES-256-CBC in Encrypter.js
